// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGghoWygHkzpgsqWhu56qhazB_L9lu1kc',
    appId: '1:1032745495782:android:0935e1ec6d7346e1a69f27',
    messagingSenderId: '1032745495782',
    projectId: 'shelterfinderapp-9b963',
    storageBucket: 'shelterfinderapp-9b963.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXQQ_qeHqe3Xfr_q1aG2P7-oVab7PonyY',
    appId: '1:1032745495782:ios:2415b6b9369d7340a69f27',
    messagingSenderId: '1032745495782',
    projectId: 'shelterfinderapp-9b963',
    storageBucket: 'shelterfinderapp-9b963.firebasestorage.app',
    iosBundleId: 'com.example.shelterFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAinaj_DsQDvvAQq-6aL-J89nzKnw8E9L0',
    appId: '1:1032745495782:web:11d3a5253576477ea69f27',
    messagingSenderId: '1032745495782',
    projectId: 'shelterfinderapp-9b963',
    authDomain: 'shelterfinderapp-9b963.firebaseapp.com',
    storageBucket: 'shelterfinderapp-9b963.firebasestorage.app',
  );

}